Implement to Json in all models
SW814F20/Application pull request #39
Opened 2020-04-01 15:35 UTC by Tricky12321

This solves #35

2020-04-01 16:03 UTC, ACmiester requested changes

2020-04-01 16:03 UTC, ACmiester commented on application/lib/model/Task.dart
> +        screenId = json['screenId'];
Får denne fejl: _TypeError (type 'List<dynamic>' is not a subtype of type 'List<int>'), når jeg logger ind på appen.

2020-04-02 12:33 UTC, ACmiester commented on application/lib/model/Task.dart
> +    String test2 = jsonEncode(json['screenId']).replaceAll('[', '').replaceAll(']', '');
Der er ikke brug for test2, og linteren bliver også glad hvis du fjerner den :D 
```suggestion
    jsonEncode(json['screenId']).replaceAll('[', '').replaceAll(']', '');
```

2020-04-02 12:36 UTC, ACmiester submitted a review, later dismissed
Looks good :)

2020-04-02 12:47 UTC, ACmiester reviewed
Looks good. No problems

2020-04-02 12:47 UTC, ACmiester commented on application/lib/model/Task.dart
> +    });
Bare så jeg selv er med.
Formålet med dette, er at vi får hver task har en collection af screenIds som den givne task indeholder, right?
Og da det ikke er sat op, så adder du bare 0 :D

2020-04-02 12:48 UTC, ACmiester submitted a review, later dismissed

2020-04-02 12:48 UTC, Tricky12321 commented on application/lib/model/Task.dart
> +    });
Fuck ja, det er sku da rigtigt

2020-04-02 12:48 UTC, Tricky12321 commented on application/lib/model/Task.dart
> +    });
```suggestion
    json['screenId'].forEach((dynamic element) {
      screenId.add(element);
    });
```

2020-04-02 12:50 UTC, ACmiester approved these changes

2020-04-02 12:51 UTC, merged