We can now delete tasks that are still notStarted
SW814F20/Application pull request #62
Opened 2020-05-18 13:28 UTC by sipman

This closes #34

2020-05-19 08:53 UTC, Tricky12321 commented
Det kan blive et problem at hvis ens device er i portrait mode, og man skal swipe mod venstre, kan man komme til at slette tasks hvis man i virkeligheden bare vil over og se tasks in-progress

Det ville også være rart hvis der var en confirm dialog hvor den lige spurgte om man var sikker på om man ville slette en task

2020-05-19 08:55 UTC, Tricky12321 commented
Jeg har heller ikke problemet du snakker om med at nogle gange så forsvinder tasks ikke

Det kan være et meget simpelt problem med internet forbindelsen eller der er lang svar tid

2020-05-19 11:49 UTC, sipman commented
@Tricky12321 Har forsøgt at løse det med potrait mode ved at ligge en lille smule margin ind, således at hvis du swiper helt ude i kanten af skærmen så rammer du ikke dismiss gesturen. Jeg har forsøgt at få det til at se nogenlunde ud - Giv mig lige en preg om du kan lide det eller om jeg skal reverse det :P

Har også lavet confirm box på deletion.

2020-05-21 09:13 UTC, Tricky12321 requested changes

2020-05-21 09:13 UTC, Tricky12321 commented on application/lib/view/screens/TasksScreen.dart
> +            padding: const EdgeInsets.all(20),
Nu ser det helt skørt ud med padding på alle sider. Det skal jo kun være på højre side

2020-05-21 09:13 UTC, Tricky12321 commented on application/lib/view/screens/TasksScreen.dart
> +            padding: const EdgeInsets.all(20),
Igen mærkelig brug af padding

2020-05-21 09:13 UTC, Tricky12321 commented on application/lib/view/screens/TasksScreen.dart
> +            padding: const EdgeInsets.all(20),
Og Igen

2020-05-21 09:54 UTC, Tricky12321 approved these changes

2020-05-21 10:32 UTC, merged